[phases.install]
cmds = [
  "sh -c 'cd server && npm install'",
  "sh -c 'cd client && npm install'"
]

[phases.build]
cmds = ["sh -c 'cd client && npm run build'"]

[start]
cmd = "node server/src/index.js"
